### ISSUE TITLE
Fishing Mechanics

### ISSUE THREAD

**Issue by camirmas** [camirmas/carts#1]
Fishing system will be based on [Hades](https://hades.fandom.com/wiki/Fishing)

### Tasks

- [x] Player must cast into a fishing spot. Fishing spots have a (not solid) hitbox that is triggered when the hook lands inside it
- [x] After a randomized amount of time (less than some limit), a bite event is triggered
- [ ] Determine the fish caught depending on whether it lives in the region and reaction time.
- [x] Display fish icon if caught
- [x] Add fish to backpack

**Comment by camirmas** [comment]
Closing, fish pool mechanics will be done in #16
